### ISSUE TITLE
verify GoReleaser binaries with cosign

### ISSUE THREAD

**Issue by developer-guy** [gythialy/golang-cross#42]
As you might know that GoReleaser signs its checksum file with cosign[^1], and store the public key within the repository[^2],  in light of this information, we can use them to verify GoReleaser binaries if it has tampered with or not.

[^1]:  https://github.com/goreleaser/goreleaser/releases/download/v0.184.0/checksums.txt.sig
[^2]: https://github.com/goreleaser/goreleaser/blob/master/cosign.pub

cc: @cpanato

**Comment by cpanato** [comment]
sounds a great idea, do you want to make this change?

**Comment by developer-guy** [comment]
yes, of course, but should we do this change within the Dockerfile, right?

**Comment by developer-guy** [comment]
PSEUDO:
```shell
# Download cosign binary
# Download checksums.txt.sig 
# Download cosign.pub
# verify checksums.txt.sig
# download GoReleaser
```

WDYT? @cpanato

**Comment by cpanato** [comment]
sounds good

**Comment by developer-guy** [comment]
@cpanato I'm assigning this to me if you don't mind. I want to work on it, is it ok for you? 🙏

**Comment by cpanato** [comment]
Go for it 🎉
