### ISSUE TITLE
error compiling for darwin

### ISSUE THREAD

**Issue by arunachalashiva** [gythialy/golang-cross#81]
Hi,
I am trying to cross compile for darwin (both amd64 and arm64) from linux and get below error. This program depends on https://github.com/cryptlex/lexactivator-go that is wrapped on top of a C library.

Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      _singleipconnect in libLexActivator.a(libcurl_la-connect.o)
      _sectransp_connect_common in libLexActivator.a(libcurl_la-sectransp.o)
      _sectransp_connect_step2 in libLexActivator.a(libcurl_la-sectransp.o)
      _sectransp_version_from_curl in libLexActivator.a(libcurl_la-sectransp.o)
Am I missing any compile/load flags?

**Comment by ranjanp75** [comment]
I have faced a similar issue and was able to fix it successfully. 
To solve this problem, the compiler rt libraries need to be installed. Please refer `https://github.com/tpoechtrager/osxcross` `build_compiler_rt.sh`. Also, please note that the clang utility installed needs to be version 12.
