### ISSUE TITLE
How to add a Linux library?

### ISSUE THREAD

**Issue by jjanvier** [gythialy/golang-cross#88]
Hello there :)
First, thanks for your work!

The package I want to build requires a special library under Linux (`libasound2-dev`). Of course it's not present in your images.

What could I do to add this library locally and be able to compile my program?

Also, what's the difference between `gythialy/golang-cross-builder` and `gythialy/golang-cross`. I didn't get it.

**Comment by gythialy** [comment]
https://github.com/gythialy/golang-cross/blob/main/Dockerfile.builder#L31-L67

`golang-cross-builder` is used as a basic image, just to improve the build speed.
